build.rs
src/main.rs

Why:
We want to correctly display the version information.

ENG-463: update version command ouput

---

Cargo.lock
Cargo.toml
build.rs
src/api/mod.rs
src/api/upgrade.rs
src/main.rs

Why:
We want to ensure we can upgrade our CLI by getting the latest release from GitHub.
How:
- adding the `upgrade` command, which lets us download the latest release on GitHub
- download the tar.gz in memory and place the file on cache, respecting XDG

ENG-304: CLI is capable of updating itself in place

---

Cargo.lock
Cargo.toml
src/api/firmwares.rs
src/api/mod.rs

Why:
We want to add the CLI logic for the `firmwares` command.
How:
- add `firmwares` related commands
- updated SDK version to support `firmwares`
- added `uuid` library for typing check given values

ENG-467: add firmwares command

---

Cargo.lock
Cargo.toml
src/api/firmwares.rs

Why:
We want to rename `firmware` to `firmware_path` and make the field required

ENG-467: firmware field changes

---

.github/workflows/new-build.yml
.github/workflows/release.yml
src/api/upgrade.rs

Why:
We want to introduce the `--version` field that allows us to download a specific version.
We also want to mark `RC` releases as prereleases when doing CI/CD.

ENG-478: improve the UX of upgrading the CLI and account for pre-releases (rc releases)

---

Cargo.lock
Cargo.toml
src/api/device_certificates.rs
src/api/devices.rs
src/api/mod.rs
src/api/products.rs

Related: #ENG-471 
Why:
We want to add `device-certificates` and `products` support to our CLI.
Notable changes:
- added base64 library
- encode certificate to base64 during `devices authentication`

ENG-484: add device-certificates command

---

.github/workflows/release.yml

Why:
We want to make sure that we mark `rc` tags as pre-release

ENG-490: fix tags not being marked as pre-release

---

Cargo.lock
Cargo.toml
src/api/mod.rs
src/api/organization_users.rs
src/api/product_users.rs

Why:
We want to add support for `organization-users` and `product-users` to our CLI.
Notes:
`organization-users create` command renamed to `organization-users add` following server guidelines

ENG-487: add CLI commands

---

Cargo.lock
Cargo.toml
src/api/devices.rs
src/api/organization_users.rs
src/api/product_users.rs

Related: ENG-496
Why:
We want to fix inconsistencies between our SDK, the API, the CLI, and the documentation.
How:
- fix device CLI inconsistencies
- fix organization-users CLI inconsistencies
- fix product-users CLI inconsistencies

ENG-491: fix inconsistencies in our CLI

---

Cargo.lock
Cargo.toml

Why:
We want to handle `500`, `409`, and `422` status code errors in our SDK.

ENG-492: improve UX for non-2xx responses

---

Cargo.lock
Cargo.toml

Why:
We want to make sure that we decode all fields correctly

ENG-496: fix field not being marked as Option

---

Cargo.lock
Cargo.toml
src/api/deployments.rs
src/api/device_certificates.rs
src/api/devices.rs
src/api/firmwares.rs
src/api/mod.rs
src/api/organization_users.rs
src/api/product_users.rs
src/api/products.rs
src/api/signing_keys.rs
src/api/users.rs
src/main.rs

**Why**
- Avoid option conflicts between global and subcommand options.
- Reduce duplicative documentation downstream.
**How**
- Only accept global options in the top level peridio command.
- Stop accepting global options directly from every subcommand.

ENG-503: move global options

---

Cargo.lock
Cargo.toml
src/api/ca_certificates.rs
src/api/deployments.rs
src/api/device_certificates.rs
src/api/devices.rs
src/api/firmwares.rs
src/api/mod.rs
src/api/organization.rs
src/api/products.rs
src/api/signing_keys.rs
src/api/upgrade.rs
src/api/users.rs
src/main.rs

Related:
ENG-501: support --ca-path PATH
ENG-505: improve error when failing to open a file or directory
ENG-504: do not require an API key for the peridio upgrade command
Why:
We want to allow for `organization-name` to be available as a global option.

ENG-502: support supplying an organization via the environment

---

src/config/mod.rs
src/main.rs

Related: ENG-530
Why:
We want to add environment variables support for `config_directory` and `profile` in our CLI

ENG-528: add global options env variables

---

Cargo.lock
Cargo.toml
src/api/deployments.rs
src/api/products.rs

Why:
We want to update our SDK to the latest changes for delta updates.

ENG-516: move delta updates to deployments

---

build.rs
src/api/deployments.rs
src/api/upgrade.rs

Why:
Fixes issues with newer versions of rust Clippy

ENG-535: fix failed clippy check

---

Cargo.lock
build.rs
src/api/upgrade.rs

**Why**
CI for Morel is planned to provide pre-built binaries for multiple targets instead of just for one.
**How**
Make the upgrade command resolve the release binary that matches its current build target instead of grabbing the first available asset.

ENG-616: multi-target support for upgrade

---

src/api/mod.rs
src/api/users.rs

```
error: The following arguments are required at the global level:
--organization-name
```

Don't require --organization-name for users me subcommand

---

Cargo.lock
Cargo.toml
src/api/mod.rs
src/api/x509.rs
src/config/config_v2.rs
src/main.rs

- Add deps: rcgen, time, and x509-parser.
- Add x509 create command.
- Allows creation of root CA, intermediate CA, and end entity certificates.
- Validity periods, common names, CA status, out dir, and issuer are configurable.
- Add config support for `certificate_authorities` section that can be referenced as part of the x509 create command a kin to how signing key pairs are referenced when creating signed binaries.

add x509 command

---

Cargo.lock
src/api/x509.rs

- x509: improve cert compatibility
- Use an implicit instead of explicit CA:FALSE to avoid potential
encoding issues in collaborating software when validating signatures.
- Add key usage and extended key usage extensions.
- bump deps

improve cert compatibility
