peridio/peridio-cli

Cargo.lock
Cargo.toml

Why:
We want to fix the issues related to uploading files using multipart

ENG-467: fix multipart issues

---

src/api/upgrade.rs

Why:
We want to improve PermissionDenied error when upgrading CLI

ENG-477: improve PermissionDenied error when upgrading CLI

---

.github/workflows/new-build.yml
src/api/upgrade.rs

Why:
We want to fix clippy issues in main

fix clippy and enable pull request CI/CD

---

Cargo.lock
Cargo.toml
src/api/deployments.rs

Why:
We want to make adjustments to the fields provided for deployments.
How:
- create a new struct for updating conditions
- make tags required
- make the version optional

ENG-468: field requirement changes for deployments

---

Cargo.lock
Cargo.toml
src/api/deployments.rs
src/api/devices.rs
src/api/firmwares.rs
src/api/mod.rs
src/api/signing_keys.rs

Why:
We want to add support for `devices` in our CLI
Additionally:
Fixes Clippy issues

ENG-470: add devices command

---

.github/workflows/new-build.yml

Why:
We want to fix issues with our CI/CD

ENG-478: fix CI/CD build

---

Cargo.lock
Cargo.toml
src/api/device_certificates.rs
src/api/devices.rs

- Make tags optional when creating devices.
- Bump Reishi to include device API fixes.
- Fix required_unless_one to use hyphens.

ENG-496: fix device command

---

Cargo.lock
Cargo.toml
src/api/ca_certificates.rs
src/api/mod.rs

Why:
We want to add support for `ca-certificates` in our CLI

ENG-493: add ca-certificates command

---

src/api/ca_certificates.rs
src/api/deployments.rs
src/api/device_certificates.rs
src/api/devices.rs
src/api/firmwares.rs
src/api/mod.rs
src/api/organization.rs
src/api/products.rs
src/api/signing_keys.rs
src/api/users.rs
src/config/mod.rs
src/main.rs

Why:
We want to support profile-based config files in our CLI

ENG-302: support profile-based config

---

Cargo.lock
Cargo.toml
src/api/binaries.rs
src/api/binary_parts.rs
src/api/binary_signatures.rs
src/api/ca_certificates.rs
src/api/config.rs
src/api/deployments.rs
src/api/device_certificates.rs
src/api/devices.rs
src/api/mod.rs
src/api/products.rs
src/api/signing_keys.rs
src/config/config_v1.rs
src/config/config_v2.rs
src/config/mod.rs
src/main.rs
src/utils/mod.rs

ENG-1052: binary signatures
ENG-1051: binary parts
ENG-567: binaries

ENG-1077: config v2

---

Cargo.lock
Cargo.toml
src/api/binaries.rs
src/api/binary_signatures.rs
src/api/config.rs
src/config/config_v2.rs
src/main.rs

fixes ENG-1103: do not serialize None api key in config
fixes ENG-1096: improve errors and use of stdout vs stdin
fixes ENG-1090: pretty print upgraded profile config

ENG-1102: improve resumability

---

Cargo.lock
Cargo.toml
src/api/binaries.rs
src/api/binary_signatures.rs
src/api/devices.rs
src/api/signing_keys.rs

fixes ENG-1110: handle signing key not found error
fixes ENG-1111: add support for a --path option
fixes ENG-1124: make devices support cohort_prn field

ENG-1095: avoid unnecessary hash recalculation

---

Cargo.lock
Cargo.toml
src/api/mod.rs
src/api/webhooks.rs
src/main.rs

Blocked by https://github.com/peridio/peridio-rust/pull/11.

add webhooks

---

Cargo.lock
Cargo.toml
src/api/binaries.rs
src/main.rs

fix binary creation

---

src/main.rs

Exit non-zero on error

---

src/api/mod.rs

improve missing argument error message

---

Cargo.lock
Cargo.toml
src/api/releases.rs

Since with an update you can change the mode and there are more arbitrary modifications, I made update being able to set the mode unlike the creation which can be calculated automatically

support for phase_mode and phase_tags

---

Cargo.lock
Cargo.toml
src/api/releases.rs

fix argument on release update

---

Cargo.lock
Cargo.toml
src/api/releases.rs

improve release help text

---

Cargo.lock
Cargo.toml
src/api/tunnels.rs

sdk update

---

Cargo.lock
Cargo.toml

fix missing tunnel response info

---

Cargo.lock
Cargo.toml
src/api/tunnels.rs

get tunnels

---

Cargo.lock
Cargo.toml
src/api/tunnels.rs

only print the response once

---

Cargo.lock
Cargo.toml
src/api/tunnels.rs

add extend tunnel

---

.github/workflows/new-build.yml
.github/workflows/release.yml

Updating CI 
references: 
https://github.com/phoenixframework/phoenix/blob/main/.github/workflows/ci.yml
https://github.com/tokio-rs/tokio/blob/master/.github/workflows/ci.yml

improve ci

---

Cargo.lock
Cargo.toml
src/api/devices.rs
src/utils/mod.rs
src/utils/serde_introspection.rs

Please leave the comments on the code, it works for us later on the road

peridio devices get-update

---

Cargo.lock
Cargo.toml
src/api/config.rs
src/api/config/profiles.rs
src/api/signing_keys.rs
src/config/config_v2.rs
src/main.rs
src/utils/mod.rs

update peridio signing-keys create

---

Cargo.lock
Cargo.toml
src/api/artifact_versions.rs
src/api/artifacts.rs
src/api/binaries.rs
src/api/bundles.rs
src/api/releases.rs
tests/integration_tests.rs

This adds admin http api operations for deletion of:
- binaries
- bundles
- releases
- artifact versions
- artifacts

support bavarb deletion

---

Cargo.lock
Cargo.toml
src/api/bundle_overrides.rs
src/api/mod.rs

**Main CRUD Operations:**
- `bundle-overrides create`
- `bundle-overrides list`
- `bundle-overrides get`
- `bundle-overrides update`
- `bundle-overrides delete`
**Device Management:**
- `bundle-overrides devices list`
- `bundle-overrides devices add`
- `bundle-overrides devices remove`

add bundle-overrides commands

---

Cargo.lock
Cargo.toml
rust-toolchain.toml

stage 1.3.1 release
